### ISSUE TITLE
the dropdown not showing.... 

### ISSUE THREAD

**Issue by gbbest15** [prof22/country_state_city_picker#13]
i cant select any country, state and city... the dropdown is not showing

**Comment by altafc22** [comment]
try csc_picker

**Comment by gbbest15** [comment]
i think i will forked the csc picker and makes some correction to it

**Comment by altafc22** [comment]
@gbbest15 Sure you can fork it and contribute it to make it more useful for community

**Comment by gbbest15** [comment]
okay thanks
