### ISSUE TITLE
Text overflow in listview

### ISSUE THREAD

**Issue by jaymeschroeder** [prof22/country_state_city_picker#22]
Some texts are too long to fit into the listview unless using small fonts as primary. I think the listview should have ways to deal with this via wrapping or cropping at least in order to make the library more functional for a wide variety of applications.

![image](https://user-images.githubusercontent.com/1024754/147582173-cc611b81-b94b-4a0d-afe2-5d8e877da1db.png)

**Comment by prof22** [comment]
Okay.. I will resolve it before the end of dec 2021.. thanks for the issue raised..

**Comment by jaymeschroeder** [comment]
This issue has been resolved. Thanks!
