### ISSUE TITLE
Mounted state check

### ISSUE THREAD

**Issue by MthokozisiMtolo** [prof22/country_state_city_picker#4]
Is it possible to add a **if(!mounted) return;** check before making calls to all instances of setState()? This would prevent an exception being thrown if the Widget is disposed before the data is loaded from the JSON file. 

**Example:**
If you have two Bottom Navs where the first will display the Country State City Picker and the second will load a different display. Navigating quickly from the Country State City Picker (before it completes loading the Countries) to the second display will throw an exception.

**Comment by prof22** [comment]
Thank You for the contribution.. I appreciate you..
